version: '3.1'

services:
  node:
    image: node:14
    working_dir: /home/node/app
    command: "yarn install --frozen-lockfile && yarn run build && yarn run start"
    volumes:
      - ../:/home/node/app
    ports:
      - "3000:3000"
